### ISSUE TITLE
Feature - change audio device for individual application

### ISSUE THREAD

**Issue by benefrasch** [frgnca/AudioDeviceCmdlets#39]
is it possible to change the output for e.g. chrome while other apps stay at the default playback device? Windows lets you configure it but it often forgets it and sets it back to default

**Comment by intel352** [comment]
I also need this ability. I have my general audio go to whatever device/channel I've designated as default, but then for videogame audio, I send to the Game device/channel. This setting is remembered by Windows when I restart the app, but it's not re-applied. Meaning, the "App volume and device preferences" GUI will show the Game channel as assigned, but I can't hear audio on that channel until I switch it away and back to Game.

Having a script for this until M$ finally (if ever) rectifies the issue would be lovely.

**Comment by Jahfry** [comment]
Stopping by to say this is what I was looking for when I stumbled on this DLL as well. 

In my case I want to be able to start an application (games) and force them onto a different device controlled by VoiceMeeter so that I can record only that application in OBS Studio. Currently the games I want to record will always set back to the "Default" device on restart as they don't have discrete output selection menus. 

My cases are similar but different to intel352's comment as my game setting is never remembered by Windows (others are, so I don't mean ALL games). However I've also seen some cases where I have his issue as well (device is remembered by Windows but has to be toggled away and then back before audio is heard). 

What I'd want is something like this:

\# (not saying these are the best syntax, just pseudo definitions to help explain the need): 

\# primary option ... set by the process EXE:
SetAudioDeviceByApplication -exe {ProcessName} <AudioDevice>

\# secondary option might be useful if multiple instances can be run but that's unusual for audio output needs:
SetAudioDeviceByApplication -pid {processID} <AudioDevice>

For my uses I'd set up a startup script that execs the application, waits a bit, then issues the command since the settings aren't saved for the game I'm using from session to session.

**Comment by jaymehta98** [comment]
Hi Jahfry, # secondary option might be useful if multiple instances can be run but that's unusual for audio output needs:
SetAudioDeviceByApplication -pid {processID} 

![image](https://user-images.githubusercontent.com/7556329/127209112-848ef0b1-d3df-4279-8559-813cb03717f3.png)

How do I get PID for 2 Webex App volume when both are Realtek? Cannot identify PID for which Webex and how do i control audio both?

**Comment by frgnca** [comment]
I do intend to add mixer support (volume control per app) as much as I can. I will refer further discussion to issue #18.
