### ISSUE TITLE
Get-AudioDevice -List  error when no enabled mic or playback device.

### ISSUE THREAD

**Issue by chetmcmasterson** [frgnca/AudioDeviceCmdlets#50]
I'm seeing behavior where Get-AudioDevice -List works iff there is at least one playback device AND one recording device enabled. I didn't have a mic enabled and it took some work to figure out that that was causing the error. Error below:

PS C:\WINDOWS\system32> Get-AudioDevice -List
Get-AudioDevice : Element not found. (Exception from HRESULT: 0x80070490)
At line:1 char:1
+ Get-AudioDevice -List
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AudioDevice], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,AudioDeviceCmdlets.GetAudioDevice

**Comment by frgnca** [comment]
> Get-AudioDevice -List works iff there is at least one playback device AND one recording device enabled. I didn't have a mic enabled and it took some work to figure out that that was causing the error.

Thank you for that information. Indeed I remember in my testing I always happened to have at least one of each.

**Comment by frgnca** [comment]
I think the issue must be on [line 167](https://github.com/frgnca/AudioDeviceCmdlets/blob/70d0a8a9a43d7f847faf531504ec1ff826824076/SOURCE/AudioDeviceCmdlets.cs#L167) when calling the List parameter, with the possibility to also happen on [line 193](https://github.com/frgnca/AudioDeviceCmdlets/blob/70d0a8a9a43d7f847faf531504ec1ff826824076/SOURCE/AudioDeviceCmdlets.cs#L193) and [line 220](https://github.com/frgnca/AudioDeviceCmdlets/blob/70d0a8a9a43d7f847faf531504ec1ff826824076/SOURCE/AudioDeviceCmdlets.cs#L220) when calling the ID and Index parameter respectively.

The way it is currently done in these lines is calling the CoreAudioApi function GetDefaultAudioEndpoint() to get a value to compare directly instead of elsewhere and possibly in a TryCatch.

**Comment by frgnca** [comment]
Will follow up this bug in issue #35
